// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace hakaton2.dataAccess.Entities;

public partial class Blog
{
    [Key]
    public int BlogId { get; set; }

    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Published { get; set; }

    public int? Category { get; set; }

    [StringLength(50)]
    public string Title { get; set; }

    [StringLength(50)]
    public string Slug { get; set; }

    [StringLength(350)]
    public string ContentHtml { get; set; }
}