// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace hakaton2.dataAccess.Entities;

public partial class Event
{
    [Key]
    [Column("eventID")]
    public int EventId { get; set; }

    [Column("title")]
    [StringLength(150)]
    public string Title { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("start", TypeName = "datetime")]
    public DateTime Start { get; set; }

    [Column("end", TypeName = "datetime")]
    public DateTime End { get; set; }

    [Column("organizerId")]
    public int OrganizerId { get; set; }

    [Column("maxParticipants")]
    public int? MaxParticipants { get; set; }

    [Column("currentParticipants")]
    public int? CurrentParticipants { get; set; }

    [Column("createdOn", TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }
}