// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace hakaton2.dataAccess.Entities;

[Table("Event")]
public partial class Event
{
    [Key]
    public int EventId { get; set; }

    [StringLength(50)]
    public string Title { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Start { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? End { get; set; }

    public int? MaxParticipants { get; set; }

    public int? CurrentParticipants { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedOn { get; set; }
}