// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace hakaton2.dataAccess.Entities;

[Table("User")]
public partial class User
{
    [Key]
    public int UserId { get; set; }

    [Required]
    [StringLength(100)]
    public string Username { get; set; }

    [Required]
    [StringLength(150)]
    public string Email { get; set; }

    public int? Points { get; set; }

    public int? Role { get; set; }

    [Required]
    public string Password { get; set; }
}